
output "random_suffix" {
  description = "A random string generated by terraform to append to resource names. This helps avoid name collisions and the test suite consumes this value."
  value       = local.random_suffix
}
